import Header from "@/components/ui/header";
import RootProvider from "@/providers";
// eslint-disable-next-line boundaries/no-unknown
import "@/styles/globals.css";
import { Inter } from "next/font/google";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
const inter = Inter({ subsets: ["latin"] })
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={inter.className} suppressHydrationWarning>
      <body className="antialiased min-h-screen ">

        <RootProvider>
          <Header />
          {children}
        </RootProvider>
      </body>
    </html>
  );
}
